name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: '[Feature]: '
labels: ['enhancement', 'triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out this form to help us understand your request.

  - type: checkboxes
    id: existing-issue
    attributes:
      label: Is there an existing feature request for this?
      description: Please search to see if a feature request already exists.
      options:
        - label: I have searched the existing issues and none match my request
          required: true

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area of the application does this feature relate to?
      options:
        - Market Data & Charts
        - Portfolio Tracking
        - Watchlist
        - DeFi Analytics
        - News & Sentiment
        - Search & Navigation
        - UI/UX
        - Performance
        - API
        - PWA / Mobile
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: Any alternative solutions or workarounds you've thought about...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Screenshots
      description: If applicable, add mockups, wireframes, or screenshots to help explain your feature.
      placeholder: Drag and drop images here or paste URLs

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Important - needed soon
        - Critical - blocking my usage
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Willing to Contribute?
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to submit a PR for this feature

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature request here.
      placeholder: Any additional information...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
