name: ❓ Question / Help Request
description: Ask a question or request help
title: '[Question]: '
labels: ['question', 'help wanted']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please fill out this form so we can assist you.

  - type: checkboxes
    id: existing-docs
    attributes:
      label: Have you checked existing resources?
      description: Please confirm you've reviewed available documentation.
      options:
        - label: I have read the README.md
          required: true
        - label: I have searched existing issues and discussions
          required: true

  - type: dropdown
    id: question-type
    attributes:
      label: Question Type
      description: What type of question is this?
      options:
        - Setup / Installation
        - Configuration
        - Usage / How-to
        - API / Data Sources
        - Contributing / Development
        - Deployment
        - Performance
        - Security
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Please describe your question in detail.
      placeholder: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context that might help us answer your question.
      placeholder: |
        - What are you trying to accomplish?
        - What have you already tried?
        - Are there any error messages?

  - type: textarea
    id: code-samples
    attributes:
      label: Code Samples
      description: If relevant, include code samples or configuration files.
      render: typescript
      placeholder: |
        // Paste relevant code here

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using? (run `node -v`)
      placeholder: e.g., v20.10.0

  - type: input
    id: package-manager
    attributes:
      label: Package Manager
      description: What package manager are you using?
      placeholder: e.g., npm 10.2.0, yarn 1.22.19, pnpm 8.10.0

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where are you running the application?
      options:
        - Local Development
        - Docker
        - Vercel
        - Netlify
        - AWS
        - Other Cloud Provider
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other information you'd like to share?
      placeholder: Any additional context...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
